# Generated by Django 4.0.2 on 2022-02-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embedathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Team Name'),
        ),
    ]
