# Generated by Django 4.0.2 on 2022-02-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embedathon', '0003_alter_team_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='max_task_visible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='embedathon.task'),
        ),
    ]
