# Generated by Django 4.1.3 on 2022-11-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedathon', '0004_alter_team_max_task_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
