# Generated by Django 4.0 on 2022-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedathon', '0006_alter_address_state_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
