# Generated by Django 4.1.3 on 2022-11-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedathon', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(default='Temp College', max_length=100, verbose_name='College Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ieee_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='IEEE Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nitk',
            field=models.BooleanField(default=False, verbose_name='NITK Student'),
        ),
    ]
