# Generated by Django 4.1.3 on 2022-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedathon', '0008_user_college_name_user_ieee_number_user_is_nitk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
